/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.tipigao.gerenciadortarefas;

import java.awt.event.*;
import java.io.File;
import java.io.FileNotFoundException;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.Icon;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileSystemView;
import javax.swing.table.AbstractTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author robertosilva
 */
public class GerenciadorTarefas extends javax.swing.JFrame {

    private int INTERVALO_ATUALIZACAO_SEGUNDOS = 1;
    private Tarefas tarefas;
    private JTableTarefasUtil tabUtil;
    private java.util.Timer temporizador;

    /**
     * Creates new form GerenciadorTarefas
     */
    public GerenciadorTarefas() {
        initComponents();

        tarefas = new Tarefas();

        tabUtil = new JTableTarefasUtil(tblTarefas);

        tblTarefas.getTableHeader().addMouseListener(new MouseAdapter() {
            @Override
            public void mouseReleased(MouseEvent e) {
                iniciarTemporizador();
            }

            @Override
            public void mousePressed(MouseEvent e) {
                //System.out.println("Mouse pressed; # of clicks: " + e.getClickCount());
                pararTemporizador();
            }

            @Override
            public void mouseClicked(MouseEvent e) {
                int col = -1;
                String nmColuna = "----";
                pararTemporizador();
                try {

                    col = tblTarefas.columnAtPoint(e.getPoint());
                    nmColuna = tblTarefas.getColumnName(col);

                    if (e.getButton() == MouseEvent.BUTTON1) {
                        //Botão esquerdo
                        //tabUtil.ordenarPor(nmColuna);

                    } else if (e.getButton() == MouseEvent.BUTTON2) {
                        //Botão do meio
                    } else if (e.getButton() == MouseEvent.BUTTON3) {
                        //Botão direito
                    }

                    iniciarTemporizador();
                } catch (Exception ex) {
                    ex.printStackTrace();
                } finally {
                    //System.out.println(col + " - " + nmColuna);
                }
            }
        });

        tblTarefas.setAutoCreateRowSorter(true);

        iniciarTemporizador();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        menuCtxTabela = new javax.swing.JPopupMenu();
        jPanel4 = new javax.swing.JPanel();
        cbxTodosProcessos = new javax.swing.JCheckBox();
        lblInfoProcessos = new javax.swing.JLabel();
        abas = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTarefas = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        btnFinalizarTarefa = new javax.swing.JButton();
        cbxTopo = new javax.swing.JCheckBox();
        btnDetalhes = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gerenciador de Tarefas");
        setMinimumSize(new java.awt.Dimension(240, 320));
        setPreferredSize(new java.awt.Dimension(640, 640));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new java.awt.GridBagLayout());

        cbxTodosProcessos.setSelected(true);
        cbxTodosProcessos.setText("Todos");

        lblInfoProcessos.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblInfoProcessos.setText("0 processos");
        lblInfoProcessos.setFocusTraversalPolicyProvider(true);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cbxTodosProcessos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 183, Short.MAX_VALUE)
                .addComponent(lblInfoProcessos, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxTodosProcessos)
                    .addComponent(lblInfoProcessos))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHEAST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.1;
        getContentPane().add(jPanel4, gridBagConstraints);

        abas.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);
        abas.setDoubleBuffered(true);

        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.LINE_AXIS));

        tblTarefas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Identificador", "Nome da sessão", "Sessão", "Memória"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblTarefas.setDoubleBuffered(true);
        jScrollPane1.setViewportView(tblTarefas);
        tblTarefas.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);

        jPanel2.add(jScrollPane1);

        abas.addTab("Tarefas", jPanel2);

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        abas.addTab("Alguma coisa aqui", jPanel1);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.BASELINE;
        gridBagConstraints.weightx = 10.0;
        gridBagConstraints.weighty = 10.0;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 0, 6);
        getContentPane().add(abas, gridBagConstraints);

        btnFinalizarTarefa.setText("Finalizar");
        btnFinalizarTarefa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinalizarTarefaActionPerformed(evt);
            }
        });

        cbxTopo.setText("Sempre no topo");
        cbxTopo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxTopoActionPerformed(evt);
            }
        });

        btnDetalhes.setText("Detalhes");
        btnDetalhes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDetalhesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cbxTopo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 253, Short.MAX_VALUE)
                .addComponent(btnDetalhes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnFinalizarTarefa)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnFinalizarTarefa)
                    .addComponent(cbxTopo)
                    .addComponent(btnDetalhes))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.1;
        getContentPane().add(jPanel3, gridBagConstraints);

        jMenu1.setText("Arquivo");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Editar");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cbxTopoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxTopoActionPerformed
        this.setAlwaysOnTop(cbxTopo.isSelected());
    }//GEN-LAST:event_cbxTopoActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        atualizaLista();
    }//GEN-LAST:event_formWindowOpened

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        pararTemporizador();
    }//GEN-LAST:event_formWindowClosing

    private void btnFinalizarTarefaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinalizarTarefaActionPerformed
        synchronized (this) {
            int[] lns = tblTarefas.getSelectedRows();

            if (lns.length == 0) {
                return;
            }

            pararTemporizador();

            ArrayList<Integer> pids = new ArrayList<Integer>();

            StringBuilder sb = new StringBuilder(
                    lns.length > 1
                            ? "Deseja realmente finalizar as seguintes tarefas?\n"
                            : "Deseja realmente finalizar a seguinte tarefa?\n"
            );

            for (int i = 0; i < lns.length; i++) {

                int ind = tblTarefas.getRowSorter().convertRowIndexToModel(lns[i]);

                String nmProcesso = (String) tblTarefas.getModel().getValueAt(ind, 0);
                String pid = (String) tblTarefas.getModel().getValueAt(ind, 1);

                sb.append(String.format("%10s", Integer.parseInt(pid)))
                        .append("     ")
                        .append(nmProcesso)
                        .append("\n");

                pids.add(Integer.parseInt(pid));
            }

            Object[] options = {"Sim", "Não", "Cancelar"};
            int r = JOptionPane.showOptionDialog(this, sb.toString(), "Finalizaar tarefa",
                    JOptionPane.DEFAULT_OPTION, JOptionPane.WARNING_MESSAGE,
                    null, options, options[1]);

            if (r == 0) {
                for (int i = 0; i < pids.size(); i++) {
                    tarefas.mataProcessoPorId(pids.get(i));
                }
                atualizaLista();
            }

            iniciarTemporizador();
        }
    }//GEN-LAST:event_btnFinalizarTarefaActionPerformed

    private void btnDetalhesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDetalhesActionPerformed
        exibeDetalheProcesso();
    }//GEN-LAST:event_btnDetalhesActionPerformed

    private void atualizaLista() {
        //synchronized (this) {
        try {
            ArrayList<TarefaItem> arTarefas = tarefas.obtemTarefas();

            int totalProcessos = arTarefas.size();

            tabUtil.atualizaDados(arTarefas);

            lblInfoProcessos.setText(String.format("%s processos",
                    //LocalDateTime.now().format( DateTimeFormatter.ofPattern("dd/MM/yyyy hh:mm:ss")),
                    totalProcessos));

        } catch (Exception ex) {
            temporizador.cancel();
            temporizador.purge();
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, ex, "Erro ao carregar a lista de tarefas", JOptionPane.ERROR_MESSAGE);
        }
        //}
    }

    private void pararTemporizador() {
        if (temporizador != null) {
            temporizador.cancel();
            temporizador.purge();
        }
    }

    private void iniciarTemporizador() {
        pararTemporizador();

        temporizador = new java.util.Timer();
        temporizador.scheduleAtFixedRate(new java.util.TimerTask() {
            @Override
            public void run() {
                atualizaLista();
            }
        }, 0, INTERVALO_ATUALIZACAO_SEGUNDOS * 1000);
    }

    private void exibeDetalheProcesso() {
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                pararTemporizador();

                int[] lns = tblTarefas.getSelectedRows();

                if (lns.length != 1) {
                    return;
                }

                int ind = tblTarefas.getRowSorter().convertRowIndexToModel(lns[0]);

                String pid = (String) tblTarefas.getModel().getValueAt(ind, 1);

                DetalheProcesso dp = new DetalheProcesso();
                dp.setPid(pid);
                dp.setVisible(true);

                iniciarTemporizador();
            }
        });
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                System.out.println("LookAndFeel: " + info.getName());
            }

            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GerenciadorTarefas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GerenciadorTarefas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GerenciadorTarefas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GerenciadorTarefas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GerenciadorTarefas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane abas;
    private javax.swing.JButton btnDetalhes;
    private javax.swing.JButton btnFinalizarTarefa;
    private javax.swing.JCheckBox cbxTodosProcessos;
    private javax.swing.JCheckBox cbxTopo;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblInfoProcessos;
    private javax.swing.JPopupMenu menuCtxTabela;
    private javax.swing.JTable tblTarefas;
    // End of variables declaration//GEN-END:variables
}
